### ISSUE TITLE
На сколько правильно добавлять tag "p" для разделения области между контентом и кнопками

### ISSUE THREAD

**Issue by aksiaaksi** [aksiaaksi/Add_Post#2]
https://github.com/aksiaaksi/Add_Post/blob/d10549c44afab48d58dc902b5c619b49bde3158b/app.js#L62-L65

#1
На сколько правильно добавлять tag "p" для разделения области между контентом и кнопками, если его на добавить кнопка like работает в по всей области кнопок, а кнопка dislike неактивна?

**Comment by coursar** [comment]
Как быстрый хак - можно, а по-хорошему, посмотри на классы https://getbootstrap.com/docs/4.3/utilities/spacing/ - они как раз добавляют отступы
